### ISSUE TITLE
API schemas

### ISSUE THREAD

**Issue by vincerubinetti** [krishnanlab/simplex#3]
Place to define/discuss all the api schemas we'll need.

🔒 - requires authentication (cookie)

## General types

```ts
// short manageable uid like youtube videos. number not good because people can guess ids by incrementing. kebab-case title frustrating because can't be changed while title field can.
type Id = string;
```

```ts
// date-time when last saved. ISO date string, e.g. 2022-11-05T19:07:55.868Z
type Date = string;
```

```ts
// first-party author (logged-in user), when reading from backend
type AuthorRead = {
  id: Id;
  name: string;
  email: string;
  institution: string;
  newsletter: boolean;
};
```

```ts
// first-party author, when writing to backend
type AuthorWrite = {
  name: string;
  email: string;
  institution: string;
  newsletter: boolean;
};
```

```ts
// third-party author (someone else), when reading from backend
type AuthorPublic = {
  id: Id;
  name: string;
  institution: string;
};
```

```ts
// "slim" version of ArticleRead used when returning (potentially long) lists of articles 
type ArticleSummary = {
  id: Id;
  date: Date;
  title: string;
  textTruncated: string; // latest revision's text, truncated to ~100 chars. users will probably remember an article more from the text in it rather than the title or source (which note, i've removed).
  collectionCount: number; // COUNT, not array of ids
};
```

```ts
// article, when reading from backend
type ArticleRead = {
  id: Id;
  revision: Id;
  author: Id;
  date: Date;
  title: string;
  source: string;
  text: string;
  ignoreWords: string[];
  collections: Id[];
};
```

```ts
// article, when writing to backend
type ArticleWrite = {
  title: string;
  source: string;
  text: string;
  ignoreWords: string[];
  collections: Id[];
};
```

```ts
// "slim" version of CollectionRead used when returning (potentially long) lists of collections 
type CollectionSummary = {
  id: Id;
  date: Date;
  title: string;
  description: string;
  articleCount: number; // COUNT, not array of ids
};
```

```ts
// collection, when reading from backend
type CollectionRead = {
  id: Id;
  author: Id;
  date: Date;
  title: string;
  description: string;
  articles: Id[];
};
```

```ts
// collection, when writing to backend
type CollectionWrite = {
  title: string;
  description: string;
  articles: Id[];
};
```

### `GET` `/current-user`

Check if user is logged in. Returns current user info if true, throws error if false.

```ts
type Response = AuthorRead; // OR ERROR
```

### `POST` `/signup`

Sign up.

```ts
type Request = AuthorWrite & {
  password: string;
  remember: boolean; // true = return persistent cookie, false = return session cookie
};
```

```ts
type Response = AuthorRead;
```

### `POST` `/login`

Log in.

```ts
type Request = {
  email: string;
  password: string;
  remember: boolean; // true = return persistent cookie, false = return session cookie
};
```

```ts
type Response = AuthorRead;
```

### `POST` `/logout` 🔒

Log out.

### `GET` `/authors/[ID]`

Lookup public info of (third-party) author.

```ts
type Response = AuthorPublic;
```

### `PUT` `/save-info` 🔒

Update account info.

```ts
type Request = AuthorWrite;
```

```ts
type Response = AuthorRead;
```

### `PUT` `/change-password` 🔒

Change password.

```ts
type Request = {
  current: string;
  fresh: string;
};
```

### `POST` `/forgot-password`

Request password reset (first step).

```ts
type Request = {
  email: string;
};
```

### `POST` `/reset-password`

Actually reset password (second step).

```ts
type Request = {
  code: string;
  email: string;
  password: string;
};
```

### `POST` `/analyze`

Run analysis on text. Need to make sure text is [split into separate words](https://github.com/krishnanlab/simplex/blob/main/app/src/util/string.ts#L9) the same way on frontend and backend.

```ts
type Request = {
  text: string; // input as raw text, tokenized (split into words) by us
  words: string[]; // OR... tokenize text (split into words) yourself
  audience: string;
  ignoreWords: string[];
};
```

Our tokenization method splits strings such that a word is a sequence of letters (any language, including diacritics), numbers, or dashes. All other characters will start a new word.

```ts
type Response = {
  scores: {
    [word: string]: number; // 0-100
  };
  complexity: number; // 0-100
  gradeLevel: number; // flesch-kincaid, 0-100
  gradeLevelText: string; // e.g. "collegiate"
  sentences: number;
  syllables: number;
  words: number;
  chars: number;
};
```

### `GET` `/simplify/[WORD]`

Get help simplifying a word.

Calls Wikipedia (and other?) api(s) to get info to show in tooltip above word to help user simplify it. Maybe we can just do this on the front end and not need an api endpoint; not sure if Wikipedia api requires api key that we'd want to not distribute in the frontend source code.

```ts
type Response = {
  definition: string;
  image: string;
  synonyms: string[];
  link: string;
};
```

### `GET` `/articles/[ID]`

Lookup latest revision of article.

```ts
type Response = ArticleRead;
```

### `GET` `/articles/[ID]/revisions`

Lookup summary of revision history of article.

```ts
type Response = { revision: Id; date: Date; }[];
```

### `GET` `/articles/[ID]/revisions/[REVISION]`

Lookup particular revision of article.

```ts
type Response = ArticleRead;
```

### `POST` `/articles/batch`

Batch lookup articles (latest revisions). Only needed for populating details when looking at another user's collection.

```ts
type Request = { ids: ID[] };
```

```ts
type Response = ArticleSummary[];
```

### `GET` `/articles` 🔒

Get list of authenticated user's articles (latest revisions).

```ts
type Response = ArticleSummary[];
```

### `POST` `/articles` ✳️🔒

Save new article. Authentication optional. If no authentication, creates anonymous article with dummy/static anonymous author id.

```ts
type Request = ArticleWrite;
```

```ts
type Response = ArticleRead;
```

### `PUT` `/articles/[ID]` 🔒

Update existing article.

```ts
type Request = ArticleWrite;
```

```ts
type Response = ArticleRead;
```

### `DELETE` `/articles/[ID]` 🔒

Delete article.

### `GET` `/collections/[ID]`

Lookup collection.

```ts
type Response = CollectionRead;
```

### `GET` `/collections` 🔒

Get list of authenticated user's collections.

```ts
type Response = CollectionSummary[];
```

### `POST` `/collections` 🔒

Save new collection.

```ts
type Request = CollectionWrite;
```

```ts
type Response = CollectionRead;
```

### `PUT` `/collections/[ID]` 🔒

Update existing collection.

```ts
type Request = CollectionWrite;
```

```ts
type Response = CollectionRead;
```

### `DELETE` `/collections/[ID]` 🔒

Delete collection.

**Comment by falquaddoomi** [comment]
Hey Vince, looks good! It'd be easier to implement if all the endpoints for a specific entity were all named the same way, e.g. all the collections-related endpoints should be "collections", not "collection". I personally prefer the plural over the singular, as it makes sense when you get all collections and when you get a specific one. In summary, that'd be "authors", "articles", and "collections" that'd need to be updated.

**Comment by vincerubinetti** [comment]
I made changes based on our discussion of implementing revisions. Instead of making the `/revisions` "sub-endpoint" return full details of the articles (possibly needing to be paginated if the number of revisions is large), I'm suggesting just having that return an ordered array of date strings. The UI will need to show the user a list of all the revisions they can jump to at once, and I'd like to show them the revision number (covered by the index of the array) and the date. Hopefully this is a small enough data structure that we can safely return all of them with no pagination. Then, in the UI, when user selects a particular revision, I'll load it on demand from the `/revisions/[REVISION]` "sub-endpoint".

Let me know if this is okay or if you want to approach it differently. However the above will most closely reflect what I need for the UI.

**Comment by falquaddoomi** [comment]
I'm good with `/article/<ID>/revisions` returning a condensed representation, and fair point, if it's condensed enough we most likely won't need pagination except in extreme cases. I'd prefer for it to be something of the form `[ {"id": X, "created_on": Y}, ... ]` than using the index of the array element as an implicit ID. You'd use the "id" field to reference the revision, e.g. `/articles/<ID>/revisions/<X>`.

**Comment by vincerubinetti** [comment]
That's good with me. It also makes it more flexible in the future if we want to return more info, like the title. I'll make updates. Going to name the fields `revision` and `date` to make them the same (a subset of) the regular `Article` types.

**Comment by vincerubinetti** [comment]
If we're worried about the number of revisions being too high, we should probably also be worried about the number of articles/collections returned from the "get user articles/collections" endpoints. Since the UI only needs these to show summary cards of articles/collections, we would add a separate data type just containing the fields needed for the summary, like `type SummaryArticle = { date: Date; title: string; source: string; collections: number; }`. Or we could keep the same data structure and just truncate `text` to some limit (as this is the only field likely to be big). Or we could paginate.

**Comment by falquaddoomi** [comment]
I like the idea of having a separate data type for the lists of articles and collections, and it's fairly easy to do in DRF. Feel free to add `SummaryArticle` (and I assume `SummaryCollection`, too) to the schema.

**Comment by vincerubinetti** [comment]
Few other small requests:

- `gradeLevel_text` to `gradeLevelText` in `/analyze`?
- add `chars` in `/analyze` along with `words`?
- `fresh` to `password` in `/reset-password`?

Obviously chars is trivial, but idk maybe nice to throw in for people using the API directly? On frontend I'll calculate words and chars in-browser for instant updates, but I'll leave the other stats to the backend.

**Comment by vincerubinetti** [comment]
Another small request. For `/analyze`, can the default audience be `general` for clarity, instead of a falsey value which it seems to be? That is, let it accept `general` for a value and also have it default to that if no value is specified?

Asking because I'd like `general` to explicitly be in the UI's url instead of `/?audience=`, and I'd like it to match the endpoints parameters too.

**Comment by vincerubinetti** [comment]
Note: I added `anonymous: boolean` to the response/return from the "create a new article" endpoint. 

I'm saving article ids of newly created articles, but only if they were done so anonymously. I could check if the frontend thinks the user is currently logged in, but this is safer since the auth is checked on the server at the moment of creation. I could also just do another query with the returned id to see if it's anonymous, but that's an extra query, and then I also have to keep track of the global/static anonymous user id in the frontend (so far I'm not doing so).
